"""recon/waf_detector.py — WAF 指纹与限流探测（REQ-161 ②/③）。

职责（recon 层，只探测）：
    - 从响应头/响应体/状态码识别常见 WAF/CDN（Cloudflare / AWS / Akamai /
      Imperva / F5 / ModSecurity / Sucuri / Wordfence / Fortinet / Barracuda）；
    - 从响应头解析速率限制参数（X-RateLimit-* / RateLimit-* / Retry-After）。

设计约束：
    - 纯函数优先（无 IO，便于单测）；网络 429 探测见 `probe_rate_limit`（Tier 2）；
    - 结果写入 `target_fingerprint`，不新建并行通道（I12）；
    - 失败不抛异常。

学术/标准依据：
    - OWASP WSTG-INFO-03（指纹识别）/ WSTG-BUSL-05（限流测试）。
    - PTES Sec2 Intelligence Gathering。
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from typing import Any

logger = logging.getLogger(__name__)

# WAF 指纹：vendor → 命中规则
#   headers: (header_name_lower, substring_or_None) —— substring=None 表示仅出现该头即可
#   cookies: cookie 名前缀
#   body:    响应体子串
#   server:  Server 头子串
_WAF_SIGNATURES: tuple[dict[str, Any], ...] = (
    {
        "vendor": "cloudflare",
        "headers": [("cf-ray", None), ("cf-cache-status", None)],
        "cookies": ["__cfduid", "__cf_bm"],
        "server": ["cloudflare"],
        "body": ["Attention Required! | Cloudflare", "Cloudflare Ray ID"],
    },
    {
        "vendor": "aws_waf",
        "headers": [("x-amzn-requestid", None), ("x-amz-cf-id", None), ("x-amzn-errortype", None)],
        "server": ["awselb", "cloudfront"],
        "body": ["Request blocked", "AWS WAF"],
    },
    {
        "vendor": "akamai",
        "headers": [("x-akamai-transformed", None), ("x-akamai-request-id", None)],
        "server": ["akamaighost", "akamai"],
        "body": ["Reference #"],
    },
    {
        "vendor": "imperva_incapsula",
        "headers": [("x-iinfo", None), ("x-cdn", "incapsula")],
        "cookies": ["incap_ses", "visid_incap"],
        "body": ["Incapsula incident ID"],
    },
    {
        "vendor": "f5_bigip",
        "headers": [("x-wa-info", None)],
        "cookies": ["bigipserver", "f5_cspm", "ts01"],
        "body": ["The requested URL was rejected"],
    },
    {
        "vendor": "modsecurity",
        "headers": [("x-mod-security", None)],
        "server": ["mod_security", "modsecurity"],
        "body": ["ModSecurity", "NAXSI"],
    },
    {
        "vendor": "sucuri",
        "headers": [("x-sucuri-id", None), ("x-sucuri-cache", None)],
        "server": ["sucuri"],
        "body": ["Access Denied - Sucuri Website Firewall"],
    },
    {
        "vendor": "wordfence",
        "body": ["wordfence", "This response was generated by Wordfence"],
    },
    {
        "vendor": "fortinet",
        "cookies": ["fortiwafsid"],
        "body": ["FortiWeb"],
    },
    {
        "vendor": "barracuda",
        "cookies": ["barra_counter_session"],
        "body": ["Barracuda"],
    },
    {
        "vendor": "cloudfront_block",
        "headers": [("x-cache", "error from cloudfront")],
    },
)

_BLOCK_BODY_MARKERS: tuple[str, ...] = (
    "access denied",
    "request blocked",
    "forbidden",
    "attention required",
    "the requested url was rejected",
    "request rejected",
    "security policy",
    "bot detection",
)


@dataclass
class RateLimitInfo:
    """Parsed rate-limit parameters from response headers."""

    limited: bool = False
    limit: int | None = None
    remaining: int | None = None
    reset_seconds: float | None = None
    retry_after_seconds: float | None = None
    raw: dict[str, str] = field(default_factory=dict)


@dataclass
class WAFReport:
    """WAF/CDN + rate-limit detection result."""

    detected: bool = False
    vendors: list[str] = field(default_factory=list)
    confidence: float = 0.0
    blocked: bool = False
    evidence: list[str] = field(default_factory=list)
    rate_limit: RateLimitInfo = field(default_factory=RateLimitInfo)


def _get_header(headers: dict[str, str], name: str) -> str | None:
    target = name.lower()
    for key, value in (headers or {}).items():
        if key.lower() == target:
            return str(value)
    return None


def parse_rate_limit_headers(headers: dict[str, str] | None) -> RateLimitInfo:
    """Extract rate-limit parameters from standard/de-facto headers."""

    def _to_float(value: str | None) -> float | None:
        if value is None:
            return None
        try:
            return float(str(value).strip())
        except (TypeError, ValueError):
            return None

    def _to_int(value: str | None) -> int | None:
        f = _to_float(value)
        return int(f) if f is not None else None

    info = RateLimitInfo()
    headers = headers or {}

    limit = _get_header(headers, "x-ratelimit-limit") or _get_header(headers, "ratelimit-limit")
    remaining = _get_header(headers, "x-ratelimit-remaining") or _get_header(headers, "ratelimit-remaining")
    reset = _get_header(headers, "x-ratelimit-reset") or _get_header(headers, "ratelimit-reset")
    retry_after = _get_header(headers, "retry-after")

    info.limit = _to_int(limit)
    info.remaining = _to_int(remaining)
    info.reset_seconds = _to_float(reset)
    info.retry_after_seconds = _to_float(retry_after)
    info.limited = any(
        v is not None for v in (info.limit, info.remaining, info.reset_seconds, info.retry_after_seconds)
    )
    for name in ("x-ratelimit-limit", "x-ratelimit-remaining", "x-ratelimit-reset", "retry-after"):
        value = _get_header(headers, name)
        if value is not None:
            info.raw[name] = value
    return info


def fingerprint_waf(
    headers: dict[str, str] | None,
    body: str = "",
    status_code: int | None = None,
    cookies: dict[str, str] | None = None,
) -> WAFReport:
    """Fingerprint a WAF/CDN from response artefacts (never raises)."""
    report = WAFReport()
    headers = headers or {}
    cookie_names = " ".join(k.lower() for k in (cookies or {}))
    body_lower = (body or "").lower()
    server_value = (_get_header(headers, "server") or "").lower()

    for sig in _WAF_SIGNATURES:
        hits: list[str] = []
        for header_name, sub in sig.get("headers", []):
            value = _get_header(headers, header_name)
            if value is None:
                continue
            if sub is None or sub.lower() in value.lower():
                hits.append(f"header:{header_name}")
        for cookie in sig.get("cookies", []):
            if cookie in cookie_names or (cookies and any(cookie in k.lower() for k in cookies)):
                hits.append(f"cookie:{cookie}")
        for sub in sig.get("server", []):
            if sub in server_value:
                hits.append(f"server:{sub}")
        for sub in sig.get("body", []):
            if sub.lower() in body_lower:
                hits.append(f"body:{sub.split()[0].lower()}")

        if hits:
            report.vendors.append(str(sig["vendor"]))
            report.evidence.extend(hits)

    if report.vendors:
        report.detected = True
        # 证据越多置信度越高（封顶 0.95）
        report.confidence = min(0.95, 0.6 + 0.1 * len(report.evidence))

    # 封锁页判定：403/406/429 + 封锁语义
    if status_code in (403, 406, 429, 503) and any(m in body_lower for m in _BLOCK_BODY_MARKERS):
        report.blocked = True
        report.evidence.append(f"block_page:status={status_code}")
        if not report.detected:
            report.detected = True
            report.confidence = max(report.confidence, 0.5)

    report.rate_limit = parse_rate_limit_headers(headers)
    return report


def waf_to_fingerprint_fields(report: WAFReport) -> dict[str, Any]:
    """Map a WAFReport into `target_fingerprint`-friendly keys."""
    return {
        "waf_detected": report.detected,
        "waf_vendors": report.vendors,
        "waf_confidence": report.confidence,
        "waf_blocked": report.blocked,
        "rate_limit": {
            "limited": report.rate_limit.limited,
            "limit": report.rate_limit.limit,
            "remaining": report.rate_limit.remaining,
            "reset_seconds": report.rate_limit.reset_seconds,
            "retry_after_seconds": report.rate_limit.retry_after_seconds,
        },
    }


async def probe_rate_limit(  # pragma: no cover - network path (Tier 2)
    url: str,
    *,
    attempts: int = 6,
    timeout: float = 5.0,
    verify: bool = True,
    headers: dict[str, str] | None = None,
) -> RateLimitInfo:
    """Burst a few requests to observe 429 / rate-limit headers.

    Network path — Tier 2 / mock range only. Never raises; returns the last
    observed rate-limit info (or an empty one).
    """
    try:
        import httpx
    except ImportError:  # pragma: no cover
        return RateLimitInfo()

    info = RateLimitInfo()
    async with httpx.AsyncClient(timeout=timeout, verify=verify) as client:
        for _ in range(max(1, attempts)):
            try:
                resp = await client.get(url, headers=headers or {})
            except Exception as e:
                logger.debug("[WAF] rate-limit probe failed: %s", e)
                break
            info = parse_rate_limit_headers(dict(resp.headers))
            if resp.status_code == 429:
                info.limited = True
                break
    return info
