# Copyright (c) 2026 OSAI Project.
# Licensed under the MIT license.

"""WAF/CDN detection probe — identify web application firewalls and CDNs.

Detects the presence of Web Application Firewalls and CDNs that may
interfere with or block red team operations:
  1. Cloudflare detection
  2. AWS CloudFront / WAF detection
  3. Akamai detection
  4. Imperva / Incapsula detection
  5. Fastly detection
  6. ModSecurity detection
  7. Generic WAF behavior (403 patterns, challenge pages)
  8. CDN edge server identification
  9. Rate limiting behavior from WAF

Architecture:
  - Input: endpoints from session.report + target URL
  - Output: waf_info (detected WAF/CDN, headers, behavior)
  - Browser: False
"""

from __future__ import annotations

import asyncio
import logging
import re
from typing import TYPE_CHECKING, Any

import httpx

from core.probes.base import ReconProbe

if TYPE_CHECKING:
    from core.session import ReconSession

logger = logging.getLogger(__name__)

# WAF/CDN signature patterns
_WAF_SIGNATURES: dict[str, dict[str, Any]] = {
    "cloudflare": {
        "headers": ["cf-ray", "cf-cache-status", "cf-connecting-ip", "__cfduid"],
        "server_header": "cloudflare",
        "body_patterns": [
            r"Cloudflare Ray ID:",
            r"cf-browser-verification",
            r"Attention Required! \| Cloudflare",
            r"cloudflareinsights\.com",
        ],
        "status_codes": [403, 503],
        "description": "Cloudflare CDN/WAF",
        "impact": "Blocks malicious requests, JavaScript challenges, rate limiting",
    },
    "aws_cloudfront": {
        "headers": ["x-amz-cf-id", "x-amz-cf-pop", "x-cache"],
        "server_header": "cloudfront",
        "body_patterns": [
            r"Generated by cloudfront",
            r"CloudFront",
        ],
        "status_codes": [403],
        "description": "AWS CloudFront CDN",
        "impact": "CDN caching, AWS WAF integration possible",
    },
    "aws_waf": {
        "headers": ["x-amzn-waf-", "x-amzn-requestid"],
        "server_header": "",
        "body_patterns": [
            r"<title>403 Forbidden</title>",
            r"Request blocked",
        ],
        "status_codes": [403],
        "description": "AWS WAF",
        "impact": "Rule-based request filtering, IP blocking, rate limiting",
    },
    "akamai": {
        "headers": ["x-akamai-", "akamai-origin-hop"],
        "server_header": "akamai",
        "body_patterns": [
            r"AkamaiGHost",
            r"Reference #\d+\.\w+",
            r"Access Denied",
        ],
        "status_codes": [403],
        "description": "Akamai CDN/WAF",
        "impact": "Advanced bot detection, behavioral analysis",
    },
    "imperva": {
        "headers": ["x-iinfo", "x-cdn", "incap-client-ip"],
        "server_header": "",
        "body_patterns": [
            r"incap_ses_",
            r"visid_incap_",
            r"Incapsula",
            r"_Incapsula_Resource",
        ],
        "status_codes": [403],
        "description": "Imperva/Incapsula WAF",
        "impact": "Bot detection, session validation, challenge pages",
    },
    "fastly": {
        "headers": ["x-served-by", "x-cache-hits", "x-timer", "fastly-"],
        "server_header": "",
        "body_patterns": [
            r"Fastly",
        ],
        "status_codes": [503],
        "description": "Fastly CDN",
        "impact": "Edge caching, WAF integration via Signal Sciences",
    },
    "modsecurity": {
        "headers": [],
        "server_header": "",
        "body_patterns": [
            r"ModSecurity",
            r"mod_security",
            r"This error was generated by Mod_Security",
            r"Not Acceptable",
            r"An appropriate representation of the requested resource",
        ],
        "status_codes": [403, 406],
        "description": "ModSecurity WAF (open source)",
        "impact": "Rule-based blocking, OWASP CRS rules",
    },
    "sucuri": {
        "headers": ["x-sucuri-", "x-sucuri-id"],
        "server_header": "sucuri",
        "body_patterns": [
            r"Sucuri",
            r"Access Denied - Sucuri",
            r"CloudProxy",
        ],
        "status_codes": [403],
        "description": "Sucuri WAF",
        "impact": "Website firewall, DDoS protection",
    },
    "f5": {
        "headers": ["x-wa-info"],
        "server_header": "bigip",
        "body_patterns": [
            r"The requested URL was rejected",
            r"Please consult with your administrator",
            r"Your support ID is:",
        ],
        "status_codes": [403],
        "description": "F5 BIG-IP ASM/WAF",
        "impact": "Enterprise WAF, advanced rule engine",
    },
}

# Generic WAF behavior indicators
_GENERIC_WAF_INDICATORS: list[tuple[re.Pattern[str], str]] = [
    (re.compile(r"(?:blocked|denied|forbidden|unauthorized|challenge).*(?:waf|firewall|security)", re.IGNORECASE), "Generic WAF block message"),
    (re.compile(r"your (?:request|ip|access) (?:has been|was|is) (?:blocked|denied|restricted)", re.IGNORECASE), "Generic IP block message"),
    (re.compile(r"please (?:enable|allow) (?:javascript|cookies)", re.IGNORECASE), "JavaScript/Cookie challenge"),
    (re.compile(r"(?:ddos|bot|spider|crawler|scanner).*(?:detect|protect|block|challenge)", re.IGNORECASE), "Bot detection message"),
]


class WAFDetectorProbe(ReconProbe):
    """WAF/CDN detection probe.

    Detects Web Application Firewalls and CDNs that may
    interfere with red team operations.

    Usage::
        probe = WAFDetectorProbe()
        result = await probe.probe(session)
        # result["detected_wafs"] -> list of detected WAFs
    """

    def __init__(self, timeout: float = 10.0) -> None:
        self._timeout = timeout

    @property
    def name(self) -> str:
        return "WAFDetectorProbe"

    @property
    def requires_browser(self) -> bool:
        return False

    @property
    def requires_auth(self) -> bool:
        return False

    async def probe(self, session: ReconSession) -> dict[str, Any]:
        """Execute WAF detection.

        Args:
            session: Recon session.

        Returns:
            Dict with detected_wafs and summary.
        """
        from urllib.parse import urlparse

        domain = urlparse(session.target_url).hostname or session.target_url
        headers = session.auth_headers if session.auth_state else {}

        detected_wafs: list[dict[str, Any]] = []

        async with httpx.AsyncClient(timeout=self._timeout, verify=False, follow_redirects=True) as client:
            for scheme in ("https", "http"):
                url = f"{scheme}://{domain}"
                try:
                    resp = await client.get(url, headers=headers)
                    # Analyze response headers
                    header_findings = self._analyze_headers(resp, url)

                    # Analyze response body
                    body_findings = self._analyze_body(resp, url)

                    # Analyze status code patterns
                    status_findings = self._analyze_status(resp, url)

                    # Also try a suspicious request to trigger WAF
                    waf_trigger_result = await self._trigger_waf(client, url, headers)

                    all_findings = header_findings + body_findings + status_findings
                    if waf_trigger_result:
                        all_findings.append(waf_trigger_result)

                    # Merge findings for the same WAF
                    merged = self._merge_waf_findings(all_findings)
                    detected_wafs.extend(merged)
                    break  # Stop after first successful connection
                except Exception:
                    continue

        # Summary
        waf_names = [w["waf_name"] for w in detected_wafs]
        generic_wafs = [w for w in detected_wafs if w["waf_name"] == "generic_waf"]

        logger.info(
            "WAFDetectorProbe: %d WAFs detected on %s (%s)",
            len(detected_wafs), domain,
            ", ".join(waf_names) if waf_names else "none",
        )

        return {
            "detected_wafs": detected_wafs,
            "summary": {
                "total": len(detected_wafs),
                "specific": [w for w in waf_names if w != "generic_waf"],
                "generic_indicators": len(generic_wafs),
                "has_waf": len(detected_wafs) > 0,
                "waf_impact": [w["impact"] for w in detected_wafs if "impact" in w],
            },
        }

    def _analyze_headers(self, resp: httpx.Response, url: str) -> list[dict[str, Any]]:
        """Analyze response headers for WAF signatures."""
        findings: list[dict[str, Any]] = []
        headers_lower = {k.lower(): v for k, v in resp.headers.items()}

        for waf_name, signature in _WAF_SIGNATURES.items():
            evidence: list[str] = []

            # Check specific headers
            for header_key in signature["headers"]:
                for actual_header in headers_lower:
                    if header_key.lower() in actual_header.lower():
                        evidence.append(f"Header: {actual_header}={headers_lower[actual_header]}")

            # Check server header
            server = headers_lower.get("server", "")
            if signature["server_header"] and signature["server_header"].lower() in server.lower():
                evidence.append(f"Server: {server}")

            if evidence:
                findings.append({
                    "waf_name": waf_name,
                    "confidence": "high" if len(evidence) >= 2 else "medium",
                    "evidence": evidence,
                    "source_url": url,
                    "detection_method": "headers",
                    "description": signature["description"],
                    "impact": signature["impact"],
                })

        return findings

    def _analyze_body(self, resp: httpx.Response, url: str) -> list[dict[str, Any]]:
        """Analyze response body for WAF signatures."""
        findings: list[dict[str, Any]] = []
        body = resp.text[:2000]

        for waf_name, signature in _WAF_SIGNATURES.items():
            evidence: list[str] = []
            for pattern in signature["body_patterns"]:
                if re.search(pattern, body):
                    evidence.append(f"Body pattern: {pattern}")

            if evidence:
                findings.append({
                    "waf_name": waf_name,
                    "confidence": "medium",
                    "evidence": evidence,
                    "source_url": url,
                    "detection_method": "body",
                    "description": signature["description"],
                    "impact": signature["impact"],
                })

        # Generic WAF indicators
        for pattern, description in _GENERIC_WAF_INDICATORS:
            match = pattern.search(body)
            if match:
                findings.append({
                    "waf_name": "generic_waf",
                    "confidence": "low",
                    "evidence": [f"Pattern: {description}"],
                    "source_url": url,
                    "detection_method": "body_generic",
                    "description": description,
                    "impact": "Unknown WAF — manual investigation needed",
                })

        return findings

    def _analyze_status(self, resp: httpx.Response, url: str) -> list[dict[str, Any]]:
        """Analyze status codes for WAF behavior."""
        findings: list[dict[str, Any]] = []

        for waf_name, signature in _WAF_SIGNATURES.items():
            if resp.status_code in signature["status_codes"]:
                findings.append({
                    "waf_name": waf_name,
                    "confidence": "low",
                    "evidence": [f"Status code: {resp.status_code}"],
                    "source_url": url,
                    "detection_method": "status_code",
                    "description": signature["description"],
                    "impact": signature["impact"],
                })

        return findings

    async def _trigger_waf(
        self, client: httpx.AsyncClient, base_url: str, headers: dict[str, str]
    ) -> dict[str, Any] | None:
        """Send suspicious requests to trigger WAF response."""
        # Test with common attack patterns
        test_urls = [
            f"{base_url.rstrip('/')}/?id=1' OR '1'='1",  # SQL injection
            f"{base_url.rstrip('/')}/<script>alert(1)</script>",  # XSS
            f"{base_url.rstrip('/')}/../../../etc/passwd",  # Path traversal
            f"{base_url.rstrip('/')}/.env",  # Config file access
        ]

        for test_url in test_urls:
            try:
                resp = await client.get(test_url, headers=headers)
                if resp.status_code == 403:
                    body = resp.text[:1000].lower()
                    # Check for WAF-specific responses
                    for waf_name, signature in _WAF_SIGNATURES.items():
                        for pattern in signature["body_patterns"]:
                            if re.search(pattern, resp.text[:2000]):
                                return {
                                    "waf_name": waf_name,
                                    "confidence": "high",
                                    "evidence": [f"Triggered WAF with: {test_url}", f"Pattern: {pattern}"],
                                    "source_url": test_url,
                                    "detection_method": "active_trigger",
                                    "description": signature["description"],
                                    "impact": signature["impact"],
                                }

                    # Generic 403
                    if any(kw in body for kw in ("blocked", "denied", "forbidden", "waf", "firewall")):
                        return {
                            "waf_name": "generic_waf",
                            "confidence": "medium",
                            "evidence": [f"Triggered 403 with: {test_url}"],
                            "source_url": test_url,
                            "detection_method": "active_trigger",
                            "description": "Generic WAF detected via active probe",
                            "impact": "Request filtering active — requires bypass strategy",
                        }
            except Exception:
                pass

        return None

    @staticmethod
    def _merge_waf_findings(findings: list[dict[str, Any]]) -> list[dict[str, Any]]:
        """Merge duplicate WAF findings, keeping highest confidence."""
        merged: dict[str, dict[str, Any]] = {}
        confidence_rank = {"high": 3, "medium": 2, "low": 1}

        for finding in findings:
            key = finding["waf_name"]
            if key not in merged:
                merged[key] = finding
                merged[key]["evidence"] = list(finding["evidence"])
                merged[key]["detection_methods"] = [finding["detection_method"]]
            else:
                existing = merged[key]
                existing["evidence"].extend(finding["evidence"])
                if finding["detection_method"] not in existing["detection_methods"]:
                    existing["detection_methods"].append(finding["detection_method"])
                # Keep highest confidence
                if confidence_rank.get(finding["confidence"], 0) > confidence_rank.get(existing["confidence"], 0):
                    existing["confidence"] = finding["confidence"]

        return list(merged.values())
