"""
build_payloads.py — 从统一的 data/payloads.py 主文件自动生成语言版本

用法:
    python scripts/build_payloads.py

输出:
    - data/payloads_cn.py  (从主文件中提取 zh 字段)
    - data/payloads_en.py  (从主文件中提取 en 字段)

生成规则:
    - 两个输出文件的 PRESET_NAMES 顺序强制一致: stealth / bruteforce / redteam / academic / minimal
    - 如果某个 preset 在目标语言中缺失，自动 fallback 到 base
    - _EXTRA_VARIANTS 直接复制（变体代码片段中英通用）
"""

import os
import sys
from datetime import datetime

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)
sys.path.insert(0, PROJECT_ROOT)

from data.payloads import PAYLOADS, _EXTRA_VARIANTS

PRESET_NAMES = ['stealth', 'bruteforce', 'redteam', 'academic', 'minimal']

# ── 验证：确保每个 payload 都有 zh/en 字段 ──
missing_zh = [k for k, v in PAYLOADS.items() if 'zh' not in v]
missing_en = [k for k, v in PAYLOADS.items() if 'en' not in v]
if missing_zh:
    print(f"[WARN] 以下 payload 缺少 zh 字段: {missing_zh}")
if missing_en:
    print(f"[WARN] 以下 payload 缺少 en 字段: {missing_en}")

# ═══════════════════════════════════════
# 模板（使用 $$PLACEHOLDER$$ 避免与 payload 内容中的 {} 冲突）
# ═══════════════════════════════════════

CN_HEADER = '''"""
OffSec AI-300 — Payload 变量定义 (中文)
来源: data/payloads.py (统一主文件)
用途: 提供 {{key}} 模板占位符的替换值
自动生成于: $$TIMESTAMP$$

⚠️  此文件由 scripts/build_payloads.py 自动生成，请勿手动编辑！
   如需修改，请编辑 data/payloads.py 主文件，然后重新运行构建脚本。

使用方式:
    from data.payloads_cn import get_payloads, get_variants
    vars_dict, presets_dict = get_payloads()
"""
from __future__ import annotations


# ═══════════════════════════════════════════════════
# 预设名称列表（用于行列转置）
# ═══════════════════════════════════════════════════

PRESET_NAMES = $$PRESET_NAMES$$


# ═══════════════════════════════════════════════════
# Payload 定义（行式结构 — 每个 payload 一行，自包含 base + 5 套 preset 值）
# 新增变量只需在此添加一个 block，无需修改多处
# ═══════════════════════════════════════════════════

PAYLOADS: dict[str, dict] = {
$$CN_PAYLOADS$$
}


_EXTRA_VARIANTS: dict[str, dict[str, str]] = {
$$EXTRA_VARIANTS$$
}


# ═══════════════════════════════════════════════════
# API: 行列转置（对外接口不变）
# ═══════════════════════════════════════════════════

def get_payloads() -> "tuple[dict[str, str], dict[str, dict[str, str]]]":
    """返回 (base_vars, presets)。

    内部将行式 PAYLOADS 转置为列式 VARS + PRESETS。
    """
    vars_dict: dict[str, str] = {}
    presets_dict: dict[str, dict[str, str]] = {pn: {} for pn in PRESET_NAMES}

    for payload_name, row in PAYLOADS.items():
        vars_dict[payload_name] = row.get("base", "")
        for pn in PRESET_NAMES:
            presets_dict[pn][payload_name] = row.get(pn, row.get("base", ""))

    return vars_dict, presets_dict


def get_variants() -> "dict[str, dict[str, str]]":
    """返回变体字典（每种攻击类型 2-5 套备选载荷）。"""
    variants: dict[str, dict[str, str]] = dict(_EXTRA_VARIANTS)
    for payload_name, row in PAYLOADS.items():
        if "variants" in row:
            variants[payload_name] = dict(row["variants"])
    return variants
'''

EN_HEADER = '''"""
OffSec AI-300 — Payload Variable Definitions (English)
Source: data/payloads.py (unified master file)
Purpose: Provide replacement values for {{key}} template placeholders
Auto-generated at: $$TIMESTAMP$$

⚠️  This file is auto-generated by scripts/build_payloads.py — DO NOT EDIT!
   To make changes, edit data/payloads.py (the master file) and re-run the build script.

Usage:
    from data.payloads_en import get_payloads, get_variants
    vars_dict, presets_dict = get_payloads()
"""
from __future__ import annotations


# ═══════════════════════════════════════════════════
# Preset name list (used for row-to-column transpose)
# ═══════════════════════════════════════════════════

PRESET_NAMES = $$PRESET_NAMES$$


# ═══════════════════════════════════════════════════
# Payload definitions (row-based structure — each payload is one row,
# self-contained with base + 5 preset values)
# To add a new variable, just add one block here — no need to modify anything else
# ═══════════════════════════════════════════════════

PAYLOADS: dict[str, dict] = {
$$EN_PAYLOADS$$
}


_EXTRA_VARIANTS: dict[str, dict[str, str]] = {
$$EXTRA_VARIANTS$$
}


# ═══════════════════════════════════════════════════
# API: Row-to-column transpose (public interface unchanged)
# ═══════════════════════════════════════════════════

def get_payloads() -> "tuple[dict[str, str], dict[str, dict[str, str]]]":
    """Return (base_vars, presets).

    Internally transposes row-based PAYLOADS into column-based VARS + PRESETS.
    """
    vars_dict: dict[str, str] = {}
    presets_dict: dict[str, dict[str, str]] = {pn: {} for pn in PRESET_NAMES}

    for payload_name, row in PAYLOADS.items():
        vars_dict[payload_name] = row.get("base", "")
        for pn in PRESET_NAMES:
            presets_dict[pn][payload_name] = row.get(pn, row.get("base", ""))

    return vars_dict, presets_dict


def get_variants() -> "dict[str, dict[str, str]]":
    """Return variants dict (2-5 alternative payloads per attack type)."""
    variants: dict[str, dict[str, str]] = dict(_EXTRA_VARIANTS)
    for payload_name, row in PAYLOADS.items():
        if "variants" in row:
            variants[payload_name] = dict(row["variants"])
    return variants
'''


def format_payload_block(lang_data: dict) -> str:
    """将 payload 的行式数据格式化为 Python 字典字符串。"""
    lines = []
    lines.append(f'        "base": {lang_data.get("base", "")!r},')
    for pn in PRESET_NAMES:
        val = lang_data.get(pn, lang_data.get('base', ''))
        lines.append(f'        {pn!r}: {val!r},')
    if 'variants' in lang_data:
        variants_str = _format_variants(lang_data['variants'])
        lines.append(f'        "variants": {variants_str},')
    return '\n'.join(lines)


def _format_variants(variants: dict) -> str:
    """格式化 variants 子字典。"""
    items = ['            ' + f'{k!r}: {v!r},' for k, v in variants.items()]
    return '{\n' + '\n'.join(items) + '\n        }'


def format_payloads_for_lang(lang: str) -> str:
    """为指定语言生成所有 payload 的格式化字符串。"""
    blocks = []
    for name in sorted(PAYLOADS.keys()):
        row = PAYLOADS[name]
        lang_data = dict(row.get(lang, row.get('zh', row.get('en', {}))))

        # 确保所有 preset 都有值（fallback 到 base）
        base = lang_data.get('base', '')
        for pn in PRESET_NAMES:
            if pn not in lang_data:
                lang_data[pn] = base

        block = format_payload_block(lang_data)
        blocks.append(f"    {name!r}: {{\n{block}\n    }},")
    return '\n\n'.join(blocks)


def format_extra_variants() -> str:
    """格式化 _EXTRA_VARIANTS。"""
    items = []
    for k, v in _EXTRA_VARIANTS.items():
        inner = ['            ' + f'{vk!r}: {vv!r},' for vk, vv in v.items()]
        items.append(f"        {k!r}: {{\n" + '\n'.join(inner) + '\n        },')
    return '\n'.join(items)


def build():
    timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    preset_names_repr = repr(PRESET_NAMES)

    cn_payloads = format_payloads_for_lang('zh')
    en_payloads = format_payloads_for_lang('en')
    extra_variants = format_extra_variants()

    # 使用 $$PLACEHOLDER$$ 替换（避免与 payload 内容中的 {} 冲突）
    def render(template: str, **replacements) -> str:
        result = template
        for key, value in replacements.items():
            result = result.replace(f'$${key}$$', value)
        return result

    # 生成 CN 文件
    cn_content = render(
        CN_HEADER,
        TIMESTAMP=timestamp,
        PRESET_NAMES=preset_names_repr,
        CN_PAYLOADS=cn_payloads,
        EXTRA_VARIANTS=extra_variants,
    )
    cn_path = os.path.join(PROJECT_ROOT, 'data', 'payloads_cn.py')
    with open(cn_path, 'w', encoding='utf-8') as f:
        f.write(cn_content)
    print(f"[OK] 已生成: {cn_path}")

    # 生成 EN 文件
    en_content = render(
        EN_HEADER,
        TIMESTAMP=timestamp,
        PRESET_NAMES=preset_names_repr,
        EN_PAYLOADS=en_payloads,
        EXTRA_VARIANTS=extra_variants,
    )
    en_path = os.path.join(PROJECT_ROOT, 'data', 'payloads_en.py')
    with open(en_path, 'w', encoding='utf-8') as f:
        f.write(en_content)
    print(f"[OK] 已生成: {en_path}")

    # 验证生成的文件可导入
    print("\n[验证] 测试导入...")
    try:
        from data.payloads_cn import get_payloads as cn_get
        cn_vars, cn_presets = cn_get()
        print(f"  CN: {len(cn_vars)} 变量, {len(cn_presets)} 预设 — OK")

        from data.payloads_en import get_payloads as en_get
        en_vars, en_presets = en_get()
        print(f"  EN: {len(en_vars)} 变量, {len(en_presets)} 预设 — OK")

        # 检查键集一致
        if cn_vars.keys() == en_vars.keys():
            print(f"  键集一致: {len(cn_vars)} 个 payload — OK")
        else:
            cn_only = set(cn_vars) - set(en_vars)
            en_only = set(en_vars) - set(cn_vars)
            if cn_only:
                print(f"  [WARN] CN 独有: {cn_only}")
            if en_only:
                print(f"  [WARN] EN 独有: {en_only}")

        # 检查 PRESET_NAMES 是否一致
        from data.payloads_cn import PRESET_NAMES as cn_pn
        from data.payloads_en import PRESET_NAMES as en_pn
        if cn_pn == en_pn:
            print(f"  PRESET_NAMES 一致: {cn_pn} — OK")
        else:
            print(f"  [WARN] PRESET_NAMES 不一致!")
            print(f"    CN: {cn_pn}")
            print(f"    EN: {en_pn}")

    except Exception as e:
        print(f"  [FAIL] 导入验证失败: {e}")
        import traceback
        traceback.print_exc()
        return False

    print("\n[DONE] 构建完成！")
    return True


if __name__ == '__main__':
    build()
