# -*- coding: utf-8 -*-
"""
Selector Pool
=============

DOM 选择器知识库：输入框、发送按钮、响应区、聊天入口、登录表单。
"""

from __future__ import annotations

from typing import Any, Dict, List

# 输入框选择器（按优先级，含评分）
INPUT_BOX_SELECTORS: List[Dict[str, Any]] = [
    {"sel": "textarea.send-box-default-text", "score": 0.95, "signals": ["precise-class"]},
    {"sel": "textarea[class*='send-box']", "score": 0.85, "signals": ["send-box-class"]},
    {"sel": "[placeholder='请输入文字或语音']", "score": 0.85, "signals": ["placeholder-zh"]},
    {"sel": "textarea[class*='chat-input']", "score": 0.80, "signals": ["chat-input-class"]},
    {"sel": "textarea[class*='message']", "score": 0.70, "signals": ["message-class"]},
    {"sel": "textarea[class*='prompt']", "score": 0.70, "signals": ["prompt-class"]},
    {"sel": "textarea:not([disabled])", "score": 0.60, "signals": ["textarea"]},
    {"sel": "[contenteditable='true'][class*='chat']", "score": 0.70, "signals": ["contenteditable", "chat-class"]},
    {"sel": "[contenteditable='true']", "score": 0.55, "signals": ["contenteditable"]},
    {"sel": "[role='textbox']", "score": 0.50, "signals": ["role-textbox"]},
    {"sel": "input[type='text'][class*='chat']", "score": 0.50, "signals": ["input", "chat-class"]},
    {"sel": "input[type='text']", "score": 0.30, "signals": ["input"]},
]

# 发送按钮选择器（按优先级）
SEND_BUTTON_SELECTORS = [
    {"sel": "button[type='submit']:not([disabled])", "score": 0.70, "signals": ["type-submit"]},
    {"sel": "button[aria-label='发送']:not([disabled])", "score": 0.95, "signals": ["aria-send-zh"]},
    {"sel": "button[aria-label='Send']:not([disabled])", "score": 0.95, "signals": ["aria-send-en"]},
    {"sel": "[aria-label='发送']:not([disabled])", "score": 0.90, "signals": ["aria-send-zh"]},
    {"sel": "[aria-label='Send']:not([disabled])", "score": 0.90, "signals": ["aria-send-en"]},
    {"sel": "button[class*='send']:not([disabled])", "score": 0.85, "signals": ["send-class"]},
    {"sel": "button[class*='submit']:not([disabled])", "score": 0.80, "signals": ["submit-class"]},
    {"sel": "[class*='send-btn']:not([disabled])", "score": 0.80, "signals": ["send-btn-class"]},
    {"sel": "[class*='submit-btn']:not([disabled])", "score": 0.75, "signals": ["submit-btn-class"]},
    {"sel": "button:has-text('发送')", "score": 0.85, "signals": ["text-send-zh"]},
    {"sel": "button:has-text('Send')", "score": 0.85, "signals": ["text-send-en"]},
    {"sel": "button:has-text('提交')", "score": 0.70, "signals": ["text-submit-zh"]},
    {"sel": "button:has-text('Submit')", "score": 0.70, "signals": ["text-submit-en"]},
    {"sel": "a:has-text('发送')", "score": 0.60, "signals": ["text-send-zh-a"]},
    {"sel": "div[role='button']:has-text('发送')", "score": 0.60, "signals": ["text-send-zh-div"]},
    {"sel": "button[type='button']:not([disabled])", "score": 0.30, "signals": ["type-button"]},
]

# 响应区域选择器
RESPONSE_SELECTORS = [
    {"sel": "[data-message-author-role='assistant']", "score": 0.90, "signals": ["openai-role"]},
    {"sel": "[class*='assistant-message']", "score": 0.85, "signals": ["assistant-msg-class"]},
    {"sel": "[class*='ai-message']", "score": 0.85, "signals": ["ai-msg-class"]},
    {"sel": "[class*='assistant-turn']", "score": 0.80, "signals": ["claude-turn"]},
    {"sel": "[class*='answer']", "score": 0.75, "signals": ["answer-class"]},
    {"sel": "[class*='response']", "score": 0.70, "signals": ["response-class"]},
    {"sel": "[class*='message-content']", "score": 0.70, "signals": ["message-content"]},
    {"sel": "[class*='chat-message']", "score": 0.65, "signals": ["chat-message"]},
    {"sel": "#messages", "score": 0.70, "signals": ["messages-id"]},
    {"sel": "#chat-container", "score": 0.60, "signals": ["chat-container-id"]},
    {"sel": "[class*='markdown']", "score": 0.60, "signals": ["markdown"]},
    {"sel": "[class*='prose']", "score": 0.55, "signals": ["prose"]},
    {"sel": "[role='log']", "score": 0.60, "signals": ["role-log"]},
    {"sel": "[aria-live='polite']", "score": 0.55, "signals": ["aria-live"]},
]

# 聊天入口兜底选择器（评分扫描未命中时使用，按常见命名排序）
CHAT_ENTRY_FALLBACK_SELECTORS = [
    ".show-chat-button", ".show-chat", ".show-chat-btn",
    ".open-chat", ".open-chat-button", ".toggle-chat",
    ".chat-fab", ".chat-widget", ".chat-trigger", ".chat-launcher",
    ".ai-assistant", ".ai-chat-btn", ".ai-trigger",
    ".floating-btn", ".fab", ".fab-btn",
    "[class*='show-chat']", "[class*='open-chat']",
    "[class*='chat-fab']", "[class*='ai-fab']",
    "[aria-label*='助手']", "[aria-label*='聊天']",
    "[aria-label*='AI']", "[aria-label*='Chat']",
    "[title*='助手']", "[title*='聊天']",
]

# 聊天入口按钮选择器（按优先级：精确 → 通用 → 兜底）
CHAT_ENTRY_SELECTORS = [
    ".smart-assistant",
    ".ai-assistant",
    ".chat-fab",
    ".chat-entry",
    ".assistant-btn",
    ".chat-bot",
    ".chatbot-btn",
    ".help-bot",
    ".customer-service",
    ".chat-widget",
    ".chat-trigger",
    ".chat-launcher",
    ".chat-toggle",
    ".virtual-assistant",
    ".va-button",
    ".bot-fab",
    ".assistant-fab",
    ".bytedance-chat",
    ".volcengine-ark",
    ".baidu-ai",
    ".aliyun-qwen",
    ".iflytek-spark",
    ".zhipu-chatglm",
    ".minimax-abab",
    ".baichuan-btn",
    ".moonshot-kimi",
    ".sensetime-nova",
    ".tencent-hunyuan",
    ".crisp-chat",
    ".intercom-launcher",
    ".tawk-chat",
    ".udesk-chat",
    ".zendesk-chat",
    ".copilot",
    ".copilot-btn",
    ".copilot-fab",
    ".copilot-launcher",
    ".github-copilot",
    ".m365-copilot",
    ".microsoft-copilot",
    ".bing-copilot",
    ".genai-btn",
    ".llm-chat",
    ".llm-btn",
    ".knowledge-base",
    ".knowledge-btn",
    ".knowledge-chat",
    ".kb-btn",
    ".kb-chat",
    ".rag-btn",
    ".rag-chat",
    ".doc-chat",
    ".doc-qa",
    ".semantic-search",
    ".ai-search",
    ".agent",
    ".agent-btn",
    ".agent-fab",
    ".ai-agent",
    ".agent-launcher",
    ".playground",
    ".ai-playground",
    ".model-playground",
    ".studio",
    ".ai-studio",
    ".workbench",
    ".chatbase-launcher",
    ".dante-launcher",
    ".customgpt-launcher",
    ".sitegpt-launcher",
    ".docsbot-launcher",
    ".botsonic-launcher",
    ".chatfast-launcher",
    ".voiceflow-launcher",
    ".ai-sidebar",
    ".ai-panel",
    ".ai-drawer",
    ".ai-modal",
    ".side-ai",
    ".floating-ai",
    ".fixed-ai",
    "[aria-label='智能助手']",
    "[aria-label='AI助手']",
    "[aria-label='智能客服']",
    "[aria-label='在线客服']",
    "[aria-label='智能问答']",
    "[aria-label='问答机器人']",
    "[aria-label='虚拟助手']",
    "[aria-label='在线咨询']",
    "[aria-label='机器人']",
    "[aria-label='聊天']",
    "[aria-label='assistant']",
    "[aria-label='Assistant']",
    "[aria-label='chat']",
    "[aria-label='Chat']",
    "[aria-label='AI Assistant']",
    "[aria-label='Virtual Assistant']",
    "[aria-label='Chatbot']",
    "[aria-label='Bot']",
    "[aria-label='Live chat']",
    "[aria-label='Open chat']",
    "[aria-label='Send message']",
    "[aria-label='Ask AI']",
    "[aria-label='Chat with AI']",
    "[aria-label='Copilot']",
    "[aria-label='AI Copilot']",
    "[aria-label='Knowledge Base']",
    "[aria-label='Agent']",
    "[aria-label='AI Agent']",
    "[aria-label='Playground']",
    "[aria-label='AI Studio']",
    "button:has-text('智能助手')",
    "button:has-text('AI助手')",
    "button:has-text('智能客服')",
    "button:has-text('在线客服')",
    "button:has-text('智能问答')",
    "button:has-text('知识库')",
    "button:has-text('智能体')",
    "button:has-text('智能搜索')",
    "button:has-text('AI搜索')",
    "button:has-text('文档问答')",
    "button:has-text('Assistant')",
    "button:has-text('Chat')",
    "button:has-text('Live Chat')",
    "button:has-text('Ask AI')",
    "button:has-text('Chat with AI')",
    "button:has-text('Copilot')",
    "button:has-text('Knowledge Base')",
    "button:has-text('AI Agent')",
    "button:has-text('Playground')",
    "button:has-text('New chat')",
    "a:has-text('智能助手')",
    "a:has-text('Chat')",
    "div[role='button']:has-text('智能助手')",
    "div[role='button']:has-text('Chat')",
    "button:has(svg)",
    "[role='button']:has(svg)",
    "a:has(svg[class])",
    "[class*='chat-icon']",
    "[class*='assistant-icon']",
    "[class*='bot-icon']",
    "[class*='ai-icon']",
    "[class*='robot-icon']",
    "img[alt*='chat']",
    "img[alt*='assistant']",
    "img[alt*='客服']",
    "img[title*='chat']",
    "img[title*='助手']",
    ".fab",
    ".fab-btn",
    ".floating-btn",
    ".float-btn",
    ".floating-action",
    "[class*='fab-right']",
    "[class*='fab-bottom']",
    "[class*='float-right']",
    "[class*='float-bottom']",
    "[class*='right-bottom']",
    "[class*='bottom-right']",
    "[class*='fixed-btn']",
    "[class*='fixed-chat']",
    "[class*='corner-btn']",
    "[data-action='chat']",
    "[data-action='assistant']",
    "[data-type='chat']",
    "[data-type='chatbot']",
    "[data-chat]",
    "[data-assistant]",
    "[data-bot]",
    "[data-action='ask-ai']",
    "[data-action='open-copilot']",
    "[data-type='ai']",
    "[data-type='copilot']",
    "[data-type='agent']",
    "[data-type='playground']",
    "[data-type='knowledge']",
    "[data-type='rag']",
    "[data-testid='ai-assistant']",
    "[data-testid='copilot-button']",
    "[data-testid='chat-fab']",
    "[class*='kefu']",
    "[class*='zhushou']",
    "[class*='jiqiren']",
    "[class*='wenda']",
    "[class*='liaotian']",
    "[class*='duihua']",
    "[class*='zhineng']",
    "[class*='zhishiku']",
    "[class*='zhinengti']",
    "[class*='assistant']",
    "[class*='chatbot']",
    "[class*='robot']",
    "[class*='chat-btn']",
    "[class*='chat-trigger']",
    "[class*='chat-launch']",
    "[class*='ai-btn']",
    "[class*='ai-fab']",
    "[class*='ai-trigger']",
    "[class*='copilot']",
    "[class*='genai']",
    "[class*='llm']",
    "[class*='rag']",
    "[class*='knowledge']",
    "[class*='agent']",
    "[class*='playground']",
    "[class*='ai-chat']",
    "[class*='ai-assistant']",
]

# 登录页检测选择器
LOGIN_PAGE_SELECTORS = {
    "username": [
        "input[name='username']",
        "input[name='account']",
        "input[name='userName']",
        "#username",
        "#account",
        "input[type='text'][placeholder*='账号']",
        "input[type='text'][placeholder*='用户']",
        "input[type='text'][placeholder*='学号']",
        "input[type='text'][placeholder*='手机']",
        "input[type='text']",
    ],
    "password": [
        "input[name='password']",
        "input[name='passwd']",
        "#password",
        "input[type='password']",
    ],
    "submit": [
        "button[type='submit']",
        "input[type='submit']",
        "button.login-btn",
        ".submit-btn",
        "button:has-text('登录')",
        "button:has-text('Login')",
        "a:has-text('登录')",
        "button:has-text('Sign')",
    ],
}
